export interface Doctor {
  id: string;
  name: string;
  specialty: string;
  description: string;
  badge?: string;
  badgeColor?: string;
  imageSrc?: string;
  gradient: string;
  icon: string;
  accentBg: string;
  accentBorder: string;
  tags: string[];
  tagColor: string;
  btnHover?: string;
  gender: "male" | "female";
  voiceId?: string;
}

export const DOCTORS: Doctor[] = [
  {
    id: "aria",
    name: "Dr. Aria",
    specialty: "General Practitioner",
    description: "Everyday illnesses, colds, infections, and general wellness questions.",
    badge: "Most Popular",
    badgeColor: "bg-sky-100 text-sky-700",
    gradient: "from-sky-400 to-sky-600",
    icon: "🩺",
    accentBorder: "border-sky-100 hover:border-sky-300",
    accentBg: "bg-sky-50",
    tags: ["Cold & Flu", "Infections", "Wellness"],
    tagColor: "bg-sky-100/80 text-sky-700",
    gender: "female",
    voiceId: "Lcf78HsYp9J51L4ay7AL", // Emily
  },
  {
    id: "kai",
    name: "Dr. Kai",
    specialty: "Mental Health Specialist",
    description: "Compassionate support for anxiety, depression, stress, and sleep disorders.",
    badge: "Top Rated",
    badgeColor: "bg-violet-100 text-violet-700",
    gradient: "from-violet-400 to-purple-600",
    icon: "🧠",
    accentBorder: "border-violet-100 hover:border-violet-300",
    accentBg: "bg-violet-50",
    tags: ["Anxiety", "Depression", "Sleep"],
    tagColor: "bg-violet-100/80 text-violet-700",
    gender: "male",
    voiceId: "pNInz6obpgnu9RA7n8uX", // Adam
  },
  {
    id: "nova",
    name: "Dr. Nova",
    specialty: "Nutritionist & Dietitian",
    description: "Expert guidance on diet, gut health, food sensitivities, and metabolic concerns.",
    badge: "New",
    badgeColor: "bg-emerald-100 text-emerald-700",
    gradient: "from-emerald-400 to-teal-600",
    icon: "🥗",
    accentBorder: "border-emerald-100 hover:border-emerald-300",
    accentBg: "bg-emerald-50",
    tags: ["Nutrition", "Gut Health", "Weight"],
    tagColor: "bg-emerald-100/80 text-emerald-700",
    gender: "female",
    voiceId: "Lcf78HsYp9J51L4ay7AL",
  },
  {
    id: "orion",
    name: "Dr. Orion",
    specialty: "Urgent Care Advisor",
    description: "Triages urgent symptoms and provides guidance on emergency care.",
    badge: "24/7",
    badgeColor: "bg-rose-100 text-rose-700",
    gradient: "from-rose-400 to-red-600",
    icon: "🚑",
    accentBorder: "border-rose-100 hover:border-rose-300",
    accentBg: "bg-rose-50",
    tags: ["Emergency", "Triage", "Pain"],
    tagColor: "bg-rose-100/80 text-rose-700",
    gender: "male",
    voiceId: "pNInz6obpgnu9RA7n8uX",
  },
  {
    id: "sol",
    name: "Dr. Sol",
    specialty: "Dermatologist",
    description: "Skin conditions, rashes, acne, eczema, and skincare recommendations.",
    badge: "Trending",
    badgeColor: "bg-amber-100 text-amber-700",
    gradient: "from-amber-400 to-yellow-600",
    icon: "🧴",
    accentBorder: "border-amber-100 hover:border-amber-300",
    accentBg: "bg-amber-50",
    tags: ["Skin", "Acne", "Eczema"],
    tagColor: "bg-amber-100/80 text-amber-700",
    gender: "male",
    voiceId: "pNInz6obpgnu9RA7n8uX",
  },
  {
    id: "vera",
    name: "Dr. Vera",
    specialty: "Cardiologist",
    description: "Heart health, blood pressure, cholesterol, and lifestyle risk factors.",
    badge: "Specialist",
    badgeColor: "bg-red-100 text-red-700",
    gradient: "from-red-400 to-rose-600",
    icon: "❤️",
    accentBorder: "border-red-100 hover:border-red-300",
    accentBg: "bg-red-50",
    tags: ["Heart", "Blood Pressure", "Cholesterol"],
    tagColor: "bg-red-100/80 text-red-700",
    gender: "female",
    voiceId: "Lcf78HsYp9J51L4ay7AL",
  },
  {
    id: "mira",
    name: "Dr. Mira",
    specialty: "Pediatrician",
    description: "Child health expert covering infant care and common childhood illnesses.",
    badge: "Family",
    badgeColor: "bg-pink-100 text-pink-700",
    gradient: "from-pink-400 to-fuchsia-600",
    icon: "👶",
    accentBorder: "border-pink-100 hover:border-pink-300",
    accentBg: "bg-pink-50",
    tags: ["Children", "Vaccines", "Development"],
    tagColor: "bg-pink-100/80 text-pink-700",
    gender: "female",
    voiceId: "Lcf78HsYp9J51L4ay7AL",
  },
  {
    id: "rex",
    name: "Dr. Rex",
    specialty: "Orthopedic Specialist",
    description: "Joint pain, sports injuries, back pain, and musculoskeletal disorders.",
    badge: "Sports",
    badgeColor: "bg-orange-100 text-orange-700",
    gradient: "from-orange-400 to-amber-600",
    icon: "🦴",
    accentBorder: "border-orange-100 hover:border-orange-300",
    accentBg: "bg-orange-50",
    tags: ["Joints", "Back Pain", "Sports"],
    tagColor: "bg-orange-100/80 text-orange-700",
    gender: "male",
    voiceId: "pNInz6obpgnu9RA7n8uX",
  },
  {
    id: "lena",
    name: "Dr. Lena",
    specialty: "Women's Health",
    description: "Reproductive health, hormonal imbalances, prenatal support, and menopause.",
    badge: "Women's",
    badgeColor: "bg-fuchsia-100 text-fuchsia-700",
    gradient: "from-fuchsia-400 to-pink-600",
    icon: "🌸",
    accentBorder: "border-fuchsia-100 hover:border-fuchsia-300",
    accentBg: "bg-fuchsia-50",
    tags: ["Hormones", "Prenatal", "PCOS"],
    tagColor: "bg-fuchsia-100/80 text-fuchsia-700",
    gender: "female",
    voiceId: "Lcf78HsYp9J51L4ay7AL",
  },
  {
    id: "zen",
    name: "Dr. Zen",
    specialty: "Sleep & Neurology",
    description: "Insomnia, migraines, neurological symptoms, and sleep apnea.",
    badge: "Neuro",
    badgeColor: "bg-indigo-100 text-indigo-700",
    gradient: "from-indigo-400 to-blue-600",
    icon: "🌙",
    accentBorder: "border-indigo-100 hover:border-indigo-300",
    accentBg: "bg-indigo-50",
    tags: ["Sleep", "Migraines", "Neurology"],
    tagColor: "bg-indigo-100/80 text-indigo-700",
    gender: "male",
    voiceId: "pNInz6obpgnu9RA7n8uX",
  },
];
